export const draconicAncestryTable = [
  {
    color: "Black",
    damage_type: "Acid",
    breath: "5 by 30 ft. line (DEX save)",
  },
  {
    color: "Blue",
    damage_type: "Lightning",
    breath: "5 by 30 ft. line (DEX save)",
  },
  {
    color: "Brass",
    damage_type: "Fire",
    breath: "5 by 30 ft. line (DEX save)",
  },
  {
    color: "Bronze",
    damage_type: "Lightning",
    breath: "5 by 30 ft. line (DEX save)",
  },
  {
    color: "Copper",
    damage_type: "Acid",
    breath: "5 by 30 ft. line (DEX save)",
  },
  {
    color: "Gold",
    damage_type: "Fire",
    breath: "15 ft. cone (DEX save)",
  },
  {
    color: "Green",
    damage_type: "Poison",
    breath: "15 ft. cone (CON save)",
  },
  {
    color: "Red",
    damage_type: "Fire",
    breath: "15 ft. cone (DEX save)",
  },
  {
    color: "Silver",
    damage_type: "Cold",
    breath: "15 ft. cone (CON save)",
  },
  {
    color: "White",
    damage_type: "Cold",
    breath: "15 ft. cone (CON save)",
  },
];

export const skillsList = [
  {
    name: "Acrobatics",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: true,
    monk: true,
    paladin: false,
    ranger: false,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Animal Handling",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: true,
    fighter: true,
    monk: false,
    paladin: false,
    ranger: true,
    rogue: false,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Arcana",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: true,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: false,
    rogue: false,
    sorcerer: true,
    warlock: true,
    wizard: true,
  },
  {
    name: "Athletics",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: false,
    fighter: true,
    monk: true,
    paladin: true,
    ranger: true,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Deception",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: false,
    rogue: true,
    sorcerer: true,
    warlock: true,
    wizard: false,
  },
  {
    name: "History",
    barbarian: false,
    bard: true,
    cleric: true,
    druid: false,
    fighter: true,
    monk: true,
    paladin: false,
    ranger: false,
    rogue: false,
    sorcerer: false,
    warlock: true,
    wizard: true,
  },
  {
    name: "Insight",
    barbarian: false,
    bard: true,
    cleric: true,
    druid: true,
    fighter: true,
    monk: true,
    paladin: true,
    ranger: true,
    rogue: true,
    sorcerer: true,
    warlock: false,
    wizard: true,
  },
  {
    name: "Intimidation",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: false,
    fighter: true,
    monk: false,
    paladin: true,
    ranger: false,
    rogue: true,
    sorcerer: true,
    warlock: true,
    wizard: false,
  },
  {
    name: "Investigation",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: true,
    rogue: true,
    sorcerer: false,
    warlock: true,
    wizard: true,
  },
  {
    name: "Medicine",
    barbarian: false,
    bard: true,
    cleric: true,
    druid: true,
    fighter: false,
    monk: false,
    paladin: true,
    ranger: false,
    rogue: false,
    sorcerer: false,
    warlock: false,
    wizard: true,
  },
  {
    name: "Nature",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: true,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: true,
    rogue: false,
    sorcerer: false,
    warlock: true,
    wizard: false,
  },
  {
    name: "Perception",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: true,
    fighter: true,
    monk: false,
    paladin: false,
    ranger: true,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Performance",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: false,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Persuasion",
    barbarian: false,
    bard: true,
    cleric: true,
    druid: false,
    fighter: false,
    monk: false,
    paladin: true,
    ranger: false,
    rogue: true,
    sorcerer: true,
    warlock: false,
    wizard: false,
  },
  {
    name: "Religion",
    barbarian: false,
    bard: true,
    cleric: true,
    druid: true,
    fighter: false,
    monk: true,
    paladin: true,
    ranger: false,
    rogue: false,
    sorcerer: true,
    warlock: true,
    wizard: true,
  },
  {
    name: "Sleight of Hand",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: false,
    monk: false,
    paladin: false,
    ranger: false,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Stealth",
    barbarian: false,
    bard: true,
    cleric: false,
    druid: false,
    fighter: false,
    monk: true,
    paladin: false,
    ranger: true,
    rogue: true,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
  {
    name: "Survival",
    barbarian: true,
    bard: true,
    cleric: false,
    druid: true,
    fighter: true,
    monk: false,
    paladin: false,
    ranger: true,
    rogue: false,
    sorcerer: false,
    warlock: false,
    wizard: false,
  },
];

export const martialMeleeWeapons = [];
