export const proficiencyMapping = {
  // Armor
  "Light Armor": "Armor",
  "Medium Armor": "Armor",
  "Heavy Armor": "Armor",
  Shields: "Armor",
  "All armor": "Armor",

  // Weapons
  "Simple Weapons": "Weapons",
  "Martial Weapons": "Weapons",
  "Hand crossbows": "Weapons",
  Longswords: "Weapons",
  Rapiers: "Weapons",
  Shortswords: "Weapons",
  Clubs: "Weapons",
  Daggers: "Weapons",
  Darts: "Weapons",
  Javelins: "Weapons",
  Maces: "Weapons",
  Quarterstaffs: "Weapons",
  Scimitars: "Weapons",
  Sickles: "Weapons",
  Slings: "Weapons",
  Spears: "Weapons",
  "Crossbows, light": "Weapons",

  // Tools
  // Musical Instruments
  Bagpipes: "Tool",
  Drum: "Tool",
  Dulcimer: "Tool",
  Flute: "Tool",
  Lute: "Tool",
  Lyre: "Tool",
  Horn: "Tool",
  "Pan Flute": "Tool",
  Shawm: "Tool",
  Viol: "Tool",
  // Artisan's Tools
  "Alchemist's Supplies": "Tool",
  "Brewer's Supplies": "Tool",
  "Calligrapher's Supplies": "Tool",
  "Carpenters's Tools": "Tool",
  "Cartographer's Tools": "Tool",
  "Cobbler's Tools": "Tool",
  "Cooks's Utensils": "Tool",
  "Glassblower's Tools": "Tool",
  "Jeweler's Tools": "Tool",
  "Leatherworkers's Tools": "Tool",
  "Mason's Tools": "Tool",
  "Painter's Supplies": "Tool",
  "Potter's Tools": "Tool",
  "Smith's Tools": "Tool",
  "Tinker's Tools": "Tool",
  "Weaver's Tools": "Tool",
  "Woodcarver's Tools": "Tool",
  // Gaming set
  "Dice set": "Tool",
  "Playing card Set": "Tool",
  // Miscellaneous Tools
  "Navigator's Tools": "Tool",
  "Thieves' Tools": "Tool",
  "Climber's Kit": "Tool",
  "Disguise Kit": "Tool",
  "Forgery Kit": "Tool",
  "Herbalism Kit": "Tool",
  "Healer's Kit": "Tool",
  "Mess Kit": "Tool",
  "Poisoner's Kit": "Tool",

  // Saving Throws
  "Saving Throw: STR": "Saving Throws",
  "Saving Throw: CON": "Saving Throws",
  "Saving Throw: DEX": "Saving Throws",
  "Saving Throw: WIS": "Saving Throws",
  "Saving Throw: INT": "Saving Throws",
  "Saving Throw: CHA": "Saving Throws",

  //Skills
  "Skill: Acrobatics": "Skills",
  "Skill: Animal Handling": "Skills",
  "Skill: Arcana": "Skills",
  "Skill: Athletics": "Skills",
  "Skill: Deception": "Skills",
  "Skill: History": "Skills",
  "Skill: Insight": "Skills",
  "Skill: Intimidation": "Skills",
  "Skill: Investigation": "Skills",
  "Skill: Medicine": "Skills",
  "Skill: Nature": "Skills",
  "Skill: Perception": "Skills",
  "Skill: Performance": "Skills",
  "Skill: Persuasion": "Skills",
  "Skill: Religion": "Skills",
  "Skill: Sleight of Hand": "Skills",
  "Skill: Stealth": "Skills",
  "Skill: Survival": "Skills",

  // Equipment
  equipment: "Equipment",
};
